### ISSUE TITLE
App says not connected while web interface works

### ISSUE THREAD

**Issue by Joel-Costamagna** [whid-injector/WHID-Mobile-Connector#12]
**Describe the bug**
When I connect to the whid injector wifi on my phone I can access the webpage and send payloads, but in the App the Whid Connexio slider is red and i cannot communicate with the device.

**Android OS version**
OxygenOS 10.0.5 GM57BA (android 10)

**WHID version**
0.0.4

**To Reproduce**
Connect to the whid injector wifi, open the app and try to send text

**Expected behavior**
I should be able to send payloads and communicate with the device

**Comment by PaulSec** [comment]
Hey Joël, thanks for reaching out. 

Did you have 4G on with the phone or just Wi-Fi?

**Comment by Joel-Costamagna** [comment]
Hi,
I tried both, the website does not load with 4g enabled, if I enable only WiFi the Web interface loads but nothing in the app

**Comment by PaulSec** [comment]
Ok, that's pretty weird. 

Would it be possible for you to take some screenshots of the app with the Wi-Fi connected: 
- of the browser being able to access the esploit app
- the whid app with the settings page (with the IP address visible)

**Comment by Joel-Costamagna** [comment]
sure, 
i tried upgrading the firmware but it didn't fix the problem.

I noticed that if i reload the app, it did not save my settings (dark theme and the wifi settings)

![image](https://user-images.githubusercontent.com/16178951/80864320-31f50600-8c82-11ea-8b12-31226132748e.png)

![image](https://user-images.githubusercontent.com/16178951/80864326-391c1400-8c82-11ea-90ed-60a0e3f371a3.png)

![image](https://user-images.githubusercontent.com/16178951/80864449-07577d00-8c83-11ea-96a7-4b3139e35da5.png)

**Comment by PaulSec** [comment]
Hi Joël, 

Someone else contacte me through private channel and has the exact same issue. After deep dive and more troubleshooting, your issue seems related with recent Android versions which are forbidding cleartext communication originating from apps.
Since ESPloit is relying on the HTTP protocol, it is in cleartext, therefore, it's forbidden. 

More details here (and some fix for the app): https://forum.ionicframework.com/t/err-cleartext-not-permitted-in-debug-app-on-android/164101/32

However, you can tweak the app in order to allow this kind of practice and this is something that I will try.

Your issue is related to this one on Github: https://github.com/whid-injector/WHID-Mobile-Connector/issues/12 (which was opened couple of days ago).

For full transparency, I pushed a new branch which should (hopefully) fix this issue and the pipeline is currently running on Github. 
You can find it here: https://github.com/whid-injector/WHID-Mobile-Connector/actions

If everything goes well, a resulting APK should be available at this address : https://github.com/whid-injector/WHID-Mobile-Connector/actions/runs/94644694 
If the apk is there, would it be possible for you to download and try it and tell me if it's working for you? I've tried it locally on my phone and it works flawlessly.

**Comment by Joel-Costamagna** [comment]
The fix works great, thank you!

**Comment by PaulSec** [comment]
w00t, pretty cool!
I will ship a v0.0.6 in this case asap (expect it to land on the Play Store in the upcoming days)

**Comment by PaulSec** [comment]
App v0.0.5 has been pushed on the Play store: https://play.google.com/store/apps/details?id=whid.usb.injector
